spring:
    application:
        name: ConfigServer
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/JohnS007/ecommerce-app-config.git
                    clone-on-start: true
server:
    port: 9296